Repository woowa-techcamp-2020/hkb-15, pull requests merged in 2020-08, with the labels that each got.

#25 Payment manager
  README.md
  client/babel.config.js
  client/package.json
  client/src/router.ts
  client/src/styles/globalstyle.scss
  client/src/styles/reset.scss
  client/src/types.ts
  client/src/utils/helper.ts
  client/src/views/header-view/index.ts
  client/src/views/header-view/styles/navigator.scss
  client/src/views/history-view/styles/history-card.scss
  client/src/views/payment-manager/index.ts
  client/src/views/payment-manager/style.scss
  client/tsconfig.json
  package-lock.json
  server/.env.example
Labels: feature

#26 feat: create history functionalities
  client/src/models/apis.ts
  client/src/models/index.ts
  client/src/types.ts
  client/src/utils/helper.ts
  client/src/views/calendar-view/index.ts
  client/src/views/create-history-view/index.ts
  client/src/views/create-history-view/styles/index.scss
  client/src/views/history-view/index.ts
  server/models/history.js
Labels: feature, frontend

#29 Create and update history functionalities
  client/src/main.ts
  client/src/models/apis.ts
  client/src/models/index.ts
  client/src/router.ts
  client/src/types.ts
  client/src/utils/helper.ts
  client/src/views/calendar-view/index.ts
  client/src/views/create-history-view/index.ts
  client/src/views/create-history-view/styles/index.scss
  client/src/views/header-view/index.ts
  client/src/views/history-view/index.ts
  client/src/views/history-view/styles/history-card.scss
  server/controllers/category.js
  server/controllers/history.js
  server/models/history.js
  server/routes/index.js
Labels: api, backend, feature, frontend

#30 Create a payment method
  client/src/assets/icons/x.svg
  client/src/styles/cards.scss
  client/src/styles/mixins.scss
  client/src/utils/helper.ts
  client/src/views/payment-manager/index.ts
  client/src/views/payment-manager/style.scss
Labels: enhancement, feature, frontend

#36 Login View and Functionalities
  client/src/models/apis.ts
  client/src/models/index.ts
  client/src/router.ts
  client/src/styles/globalstyle.scss
  client/src/views/header-view/index.ts
  client/src/views/login-view/index.ts
  client/src/views/login-view/styles/index.scss
  server/.env.example
  server/app.js
  server/controllers/history.js
  server/controllers/payment.js
  server/controllers/user.js
  server/package-lock.json
  server/package.json
  server/routes/index.js
  server/utils/auth.js
Labels: api, backend, feature, frontend

#39 Integrate woowahan chart
  client/package-lock.json
  client/package.json
  client/src/styles/globalstyle.scss
  client/src/views/analytics-view/index.ts
  client/src/views/analytics-view/styles/index.scss
  client/src/views/calendar-view/index.ts
  client/src/views/calendar-view/styles/index.scss
  client/src/views/create-history-view/index.ts
  client/src/views/header-view/index.ts
  client/src/views/header-view/styles/index.scss
  client/src/views/header-view/styles/navigator.scss
  client/src/views/header-view/styles/sum-selector.scss
  client/src/views/history-view/index.ts
  client/src/views/history-view/styles/index.scss
  client/src/views/payment-manager/style.scss
Labels: feature, frontend

#41 LoginView UI
  client/src/styles/globalstyle.scss
  client/src/views/login-view/index.ts
  client/src/views/login-view/styles/index.scss
Labels: feature, frontend

#42 Modularize Woowa ORM
  server/controllers/history.js
  server/controllers/payment.js
  server/models/category.js
  server/models/history.js
  server/models/index.js
  server/models/model.js
  server/models/payment.js
  server/models/user.js
  server/package-lock.json
  server/package.json
Labels: backend, database

#43 Endgame by jhaemin
  .gitignore
  client/.postcssrc
  client/babel.config.js
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/src/styles/reset.scss
  client/src/views/analytics-view/index.ts
  client/src/views/analytics-view/styles/index.scss
  client/src/views/calendar-view/index.ts
  client/src/views/create-history-view/index.ts
  client/src/views/create-history-view/styles/index.scss
  client/src/views/header-view/index.ts
  client/src/views/history-view/index.ts
  client/src/views/login-view/index.ts
Labels: enhancement, fix, frontend

#44 Endgame by zoomKoding
  server/.env.example
  server/demo-data.sql
  server/models/index.js
  server/package-lock.json
  server/package.json
  server/utils/auth.js
Labels: backend, enhancement, fix
