Repository woowa-techcamp-2020/hkb-15, pull requests merged in 2020-07, with the labels that each got.

#2 env: setting up the backend environment
  .prettierrc
  server/.eslintrc.js
  server/app.js
  server/bin/www
  server/controllers/user.js
  server/models/index.js
  server/models/model.js
  server/models/user.js
  server/package-lock.json
  server/package.json
  server/routes/index.js
  server/routes/user.js
  server/utils/auth.js
  server/utils/helper.js
Labels: backend, config

#7 refactor: apply suggestions
  client/src/index.html
  client/src/styles/globalstyle.scss
  client/src/styles/variables.scss
  client/src/views/header-view/index.ts
  client/src/views/header-view/styles/index.scss
  client/src/views/header-view/styles/month-selector.scss
  client/src/views/header-view/styles/navigator.scss
  client/src/views/header-view/styles/sum-selector.scss
  client/src/views/history-view/index.ts
  client/src/views/history-view/styles/history-card.scss
  client/src/views/history-view/styles/index.scss
Labels: enhancement

#9 feat: add history view functionalities
  client/src/models/index.ts
  client/src/router.ts
  client/src/styles/variables.scss
  client/src/types.ts
  client/src/utils/helper.ts
  client/src/views/header-view/index.ts
  client/src/views/header-view/styles/month-selector.scss
  client/src/views/history-view/index.ts
  client/src/views/history-view/styles/date-indicator.scss
  client/src/views/history-view/styles/history-card.scss
  client/src/views/history-view/styles/index.scss
Labels: feature, frontend

#14 feat: history view functionalities
  client/src/main.ts
  client/src/models/index.ts
  client/src/router.ts
  client/src/utils/helper.ts
  client/src/views/header-view/index.ts
  client/src/views/header-view/styles/month-selector.scss
  client/src/views/header-view/styles/sum-selector.scss
  client/src/views/history-view/index.ts
  client/src/views/history-view/styles/index.scss
Labels: feature, frontend

#15 Feat/ui/cards
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/src/styles/cards.scss
  client/src/styles/globalstyle.scss
  client/src/views/header-view/styles/index.scss
  client/src/views/header-view/styles/month-selector.scss
  client/src/views/header-view/styles/navigator.scss
  package-lock.json
  package.json
  server/app.js
  server/package-lock.json
  server/package.json
Labels: feature, frontend

#16 feat: create calendar UI
  client/src/main.ts
  client/src/router.ts
  client/src/types.ts
  client/src/utils/helper.ts
  client/src/views/calendar-view/index.ts
  client/src/views/calendar-view/styles/index.scss
Labels: feature, frontend
